name: Publish Pipeline

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.13]

    environment:
      name: pypi
      url: https://pypi.org/p/criteria-pattern/

    permissions:
      id-token: write

    name: Publish Pipeline
    timeout-minutes: 5
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Only last commit

      - name: 🐍 Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: 📦 Install dependencies
        run: pip install build

      - name: 🛠️ Build distribution
        run: python -m build

      - name: 🫙 Store distribution package
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: 🚀 Publish
        uses: pypa/gh-action-pypi-publish@2f6f737ca5f74c637829c0f5c3acd0e29ea5e8bf
